# Site settings
title: 古城童话
description: > # this means to ignore newlines until "baseurl:"
    古城童话的个人主页
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: rouge
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: liuenyangithubio # add disqus shortname here

# author info
# add your appropriate info here
author: liuenyan # your name
bio:    Python爱好者 # your bio
email: liu.enyan@gmail.com
email_md5: ab89c8cae084f1d39d2f0b4c0203f5f2 # md5 hash of your email
twitter_username: liuenyan 
github_username: liuenyan

# Theming options
# These settings are mandatory.
# theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
